[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]


remappings = [
    "@chainlink=lib/chainlink/contracts",
    "@solmate/=lib/solmate/src",
] # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256 # fuzz testing number of set runs - change this to test more
